In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
data.shape

(150, 6)

In [9]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [13]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [15]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [17]:
x = data.iloc[:,1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [19]:
y = data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [21]:
# x values feature scaling

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [29]:
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [79]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [81]:
x_train.shape

(120, 4)

In [83]:
x_test.shape

(30, 4)

In [39]:
 # Model Training

In [105]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 7)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [107]:
pred = model.predict(x_test)
pred[0:5]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor'], dtype=object)

In [109]:
y_test[0:5]

17        Iris-setosa
96    Iris-versicolor
22        Iris-setosa
8         Iris-setosa
63    Iris-versicolor
Name: Species, dtype: object

In [47]:
# To check Accuracy

In [111]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy

0.9666666666666667

In [53]:
# Confusion Matrix

In [113]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)
cm

array([[14,  0,  0],
       [ 0,  8,  0],
       [ 0,  1,  7]], dtype=int64)

In [57]:
# To take correct K value


In [115]:
correct_sum = []
for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors = i )
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct)

In [117]:
correct_sum

[30, 30, 30, 29, 30, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30]

In [119]:
result = pd.DataFrame(data = correct_sum)
result.index = result.index+1
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  30  30  30  29  30  29  29  29  29  29  30  30  30  30  30  30  30  30  30

In [121]:
# Model Train
model = KNeighborsClassifier(n_neighbors = 15)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [123]:
accuracy_score(y_test,pred)

1.0

In [125]:
cm1 = confusion_matrix(y_test,pred)
cm1

array([[14,  0,  0],
       [ 0,  8,  0],
       [ 0,  0,  8]], dtype=int64)